let Films = [
  {
    id: Math.random() * 1000000,
    name: "Parasite",
    img:
      "https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX182_CR0,0,182,268_AL_.jpg",
    genres: "Comedy | Drama | Thriller",
    releaseDate: "7 February 2020",
    director: "Bong Joon Ho",
    description:
      "The Kims - mother and father Chung-sook and Ki-taek, and their young adult offspring, son Ki-woo and daughter Ki-jung - are a poor family living in a shabby and cramped half basement apartment in a busy lower working class commercial district of Seoul",
    ratting: 8.6,
    reviews: 396631,
    Country: "South Korea",
    Language: "Korean",
    Runtime: "132 min",
    isFav: true,
  },
  {
    id: Math.random() * 1000000,
    name: "Joker",
    img:
      "https://media.senscritique.com/media/000018727645/source_big/Joker.jpg",
    genres: "Comedy | Drama | Thriller",
    releaseDate: "7 February 2020",
    director: "Bong Joon Ho",
    description:
      "The Kims - mother and father Chung-sook and Ki-taek, and their young adult offspring, son Ki-woo and daughter Ki-jung - are a poor family living in a shabby and cramped half basement apartment in a busy lower working class commercial district of Seoul",
    ratting: 8.6,
    reviews: 396631,
    Country: "South Korea",
    Language: "Korean",
    Runtime: "132 min",
    isFav: true,
  },
  {
    id: Math.random() * 1000000,
    name: "Parasite",
    img:
      "https://img5.cdn.cinoche.com/images/5c17b251b017529a75e490cd3067be61.jpg",
    genres: "Comedy | Drama | Thriller",
    releaseDate: "7 February 2020",
    director: "Bong Joon Ho",
    description:
      "The Kims - mother and father Chung-sook and Ki-taek, and their young adult offspring, son Ki-woo and daughter Ki-jung - are a poor family living in a shabby and cramped half basement apartment in a busy lower working class commercial district of Seoul",
    ratting: 8.6,
    reviews: 396631,
    Country: "South Korea",
    Language: "Korean",
    Runtime: "132 min",
    isFav: false,
  },
  {
    id: Math.random() * 1000000,
    name: "Parasite",
    img:
      "https://img5.cdn.cinoche.com/images/5c17b251b017529a75e490cd3067be61.jpg",
    genres: "Comedy | Drama | Thriller",
    releaseDate: "7 February 2020",
    director: "Bong Joon Ho",
    description:
      "The Kims - mother and father Chung-sook and Ki-taek, and their young adult offspring, son Ki-woo and daughter Ki-jung - are a poor family living in a shabby and cramped half basement apartment in a busy lower working class commercial district of Seoul",
    ratting: 8.6,
    reviews: 396631,
    Country: "South Korea",
    Language: "Korean",
    Runtime: "132 min",
    isFav: false,
  },
  {
    id: Math.random() * 1000000,
    name: "Parasite",
    img:
      "https://img-4.linternaute.com/9o4jRd4WGGXJmmSMo5MGKas9BfM=/405x540/56468ff5707640949f8a2404b25ac5f2/ccmcms-linternaute/186902.jpg",
    genres: "Comedy | Drama | Thriller",
    releaseDate: "7 February 2020",
    director: "Bong Joon Ho",
    description:
      "The Kims - mother and father Chung-sook and Ki-taek, and their young adult offspring, son Ki-woo and daughter Ki-jung - are a poor family living in a shabby and cramped half basement apartment in a busy lower working class commercial district of Seoul",
    ratting: 8.6,
    reviews: 396631,
    Country: "South Korea",
    Language: "Korean",
    Runtime: "132 min",
    isFav: false,
  },
  {
    id: Math.random() * 1000000,
    name: "Parasite",
    img:
      "https://i.pinimg.com/474x/ac/2f/58/ac2f58d9275e2399279c1fda4220178c.jpg",
    genres: "Comedy | Drama | Thriller",
    releaseDate: "7 February 2020",
    director: "Bong Joon Ho",
    description:
      "The Kims - mother and father Chung-sook and Ki-taek, and their young adult offspring, son Ki-woo and daughter Ki-jung - are a poor family living in a shabby and cramped half basement apartment in a busy lower working class commercial district of Seoul",
    ratting: 8.6,
    reviews: 396631,
    Country: "South Korea",
    Language: "Korean",
    Runtime: "132 min",
    isFav: true,
  },
  {
    id: Math.random() * 1000000,
    name: "Parasite",
    img:
      "https://i.pinimg.com/474x/fd/5e/66/fd5e662dce1a3a8cd192a5952fa64f02--classic-poster-classic-movies-posters.jpg",
    genres: "Comedy | Drama | Thriller",
    releaseDate: "7 February 2020",
    director: "Bong Joon Ho",
    description:
      "The Kims - mother and father Chung-sook and Ki-taek, and their young adult offspring, son Ki-woo and daughter Ki-jung - are a poor family living in a shabby and cramped half basement apartment in a busy lower working class commercial district of Seoul",
    ratting: 8.6,
    reviews: 396631,
    Country: "South Korea",
    Language: "Korean",
    Runtime: "132 min",
    isFav: true,
  },
  {
    id: Math.random() * 1000000,
    name: "Parasite",
    img:
      "https://images-na.ssl-images-amazon.com/images/I/71rNJQ2g-EL._AC_SL1178_.jpg",
    genres: "Comedy | Drama | Thriller",
    releaseDate: "7 February 2020",
    director: "Bong Joon Ho",
    description:
      "The Kims - mother and father Chung-sook and Ki-taek, and their young adult offspring, son Ki-woo and daughter Ki-jung - are a poor family living in a shabby and cramped half basement apartment in a busy lower working class commercial district of Seoul",
    ratting: 8.6,
    reviews: 396631,
    Country: "South Korea",
    Language: "Korean",
    Runtime: "132 min",
    isFav: true,
  },
  {
    id: Math.random() * 1000000,
    name: "Parasite",
    img:
      "https://s3.birthmoviesdeath.com/images/made/X-Men-Dark-Phoenix-New-Poster_1200_1777_81_s.jpg",
    genres: "Comedy | Drama | Thriller",
    releaseDate: "7 February 2020",
    director: "Bong Joon Ho",
    description:
      "The Kims - mother and father Chung-sook and Ki-taek, and their young adult offspring, son Ki-woo and daughter Ki-jung - are a poor family living in a shabby and cramped half basement apartment in a busy lower working class commercial district of Seoul",
    ratting: 8.6,
    reviews: 396631,
    Country: "South Korea",
    Language: "Korean",
    Runtime: "132 min",
    isFav: false,
  },
  {
    id: Math.random() * 1000000,
    name: "Parasite",
    img:
      "https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX182_CR0,0,182,268_AL_.jpg",
    genres: "Comedy | Drama | Thriller",
    releaseDate: "7 February 2020",
    director: "Bong Joon Ho",
    description:
      "The Kims - mother and father Chung-sook and Ki-taek, and their young adult offspring, son Ki-woo and daughter Ki-jung - are a poor family living in a shabby and cramped half basement apartment in a busy lower working class commercial district of Seoul",
    ratting: 8.6,
    reviews: 396631,
    Country: "South Korea",
    Language: "Korean",
    Runtime: "132 min",
    isFav: false,
  },
  {
    id: Math.random() * 1000000,
    name: "Parasite",
    img:
      "https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX182_CR0,0,182,268_AL_.jpg",
    genres: "Comedy | Drama | Thriller",
    releaseDate: "7 February 2020",
    director: "Bong Joon Ho",
    description:
      "The Kims - mother and father Chung-sook and Ki-taek, and their young adult offspring, son Ki-woo and daughter Ki-jung - are a poor family living in a shabby and cramped half basement apartment in a busy lower working class commercial district of Seoul",
    ratting: 8.6,
    reviews: 396631,
    Country: "South Korea",
    Language: "Korean",
    Runtime: "132 min",
    isFav: false,
  },
  {
    id: Math.random() * 1000000,
    name: "Parasite",
    img:
      "https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX182_CR0,0,182,268_AL_.jpg",
    genres: "Comedy | Drama | Thriller",
    releaseDate: "7 February 2020",
    director: "Bong Joon Ho",
    description:
      "The Kims - mother and father Chung-sook and Ki-taek, and their young adult offspring, son Ki-woo and daughter Ki-jung - are a poor family living in a shabby and cramped half basement apartment in a busy lower working class commercial district of Seoul",
    ratting: 8.6,
    reviews: 396631,
    Country: "South Korea",
    Language: "Korean",
    Runtime: "132 min",
    isFav: false,
  },
  {
    id: Math.random() * 1000000,
    name: "Parasite",
    img:
      "https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX182_CR0,0,182,268_AL_.jpg",
    genres: "Comedy | Drama | Thriller",
    releaseDate: "7 February 2020",
    director: "Bong Joon Ho",
    description:
      "The Kims - mother and father Chung-sook and Ki-taek, and their young adult offspring, son Ki-woo and daughter Ki-jung - are a poor family living in a shabby and cramped half basement apartment in a busy lower working class commercial district of Seoul",
    ratting: 8.6,
    reviews: 396631,
    Country: "South Korea",
    Language: "Korean",
    Runtime: "132 min",
    isFav: false,
  },
];

export default Films;
